name = "nakhon-queue"
compatibility_date = "2024-09-03"
type = "javascript"

[site]
bucket = "./public"
entry-point = "./"

[[kv_namespaces]]
binding = "QUEUE"
id = "271878c58f2f4094a9a7f7a3066aa822"
preview_id = "271878c58f2f4094a9a7f7a3066aa822"

